Symfony 6 compatibility in composer.json
PUGX/shortid-doctrine-bundle pull request #10
Opened 2021-12-17 10:09 UTC by spackmat

Just adds the 6.x versions of Symfony packages to composer.json. Seems as that works well.

BTW it could be a good idea to switch to pugx/shortid-doctrine 1.0 that was released some weeks ago. But I didn't try that, yet.

2021-12-17 14:48 UTC, garak requested changes
Please go on with raising deps, I'm not interested in supporting sf6 in 0.X

2021-12-17 15:13 UTC, spackmat commented
What do you mean by "Please go on with raising deps"? Do you mean raising `pugx/shortid-doctrine` to `^1.0`? I removed that to not conflict with PR #9

2021-12-17 16:17 UTC, garak commented
You can go on. Other PR is closed

2021-12-17 17:01 UTC, spackmat commented
@garak OK, also raised `pugx/shortid-doctrine` to `^1.0` again.

2021-12-19 15:25 UTC, garak approved these changes

2021-12-19 15:25 UTC, merged

2021-12-19 15:25 UTC, garak commented
thank you!